import assert from "node:assert/strict";
import test from "node:test";

const sdkPath = process.env.SDK_SOURCE_TEST === "1" ? "../src/index.ts" : "../dist/index.js";
const { deriveLaunchPoolRecipe, deriveLaunchPositionRanges, getSqrtRatioAtTick } = await import(sdkPath);

const Q96 = 1n << 96n;
const MAX_UINT128 = (1n << 128n) - 1n;
const MAX_INT128 = (1n << 127n) - 1n;
const MAX_UINT256 = (1n << 256n) - 1n;
const SUPPLY = 1_000_000_000n * 10n ** 18n;
const ceil = (numerator, denominator) => (numerator + denominator - 1n) / denominator;
const sum = (items, field) => items.reduce((total, item) => total + item[field], 0n);

// Independent literal five-position vectors from Black Market's generated
// presets at launch tick 0, spacing 60. Token1 vectors are explicitly listed,
// not generated by reflecting the implementation's token0 ranges.
const TOPOLOGIES = {
  "smooth-ramp": {
    weights: [1111, 1556, 2000, 2444, 2889],
    widths: [16, 14, 13, 11, 10],
    gaps: [0, 0, 0, 0],
    token0: [[0, 960], [960, 1800], [1800, 2580], [2580, 3240], [3240, 3840]],
    token1: [[-960, 0], [-1800, -960], [-2580, -1800], [-3240, -2580], [-3840, -3240]],
    allocated: [111_100n, 155_600n, 200_000n, 244_400n, 288_903n],
  },
  staircase: {
    weights: [323, 322, 1290, 2904, 5161],
    widths: [6, 6, 11, 18, 23],
    gaps: [0, 3, 3, 3],
    token0: [[0, 360], [360, 720], [900, 1560], [1740, 2820], [3000, 4380]],
    token1: [[-360, 0], [-720, -360], [-1560, -900], [-2820, -1740], [-4380, -3000]],
    allocated: [32_300n, 32_200n, 129_000n, 290_400n, 516_103n],
  },
  "early-scarcity": {
    weights: [302, 585, 1434, 2849, 4830],
    widths: [5, 9, 13, 17, 20],
    gaps: [3, 4, 5, 6],
    token0: [[0, 300], [480, 1020], [1260, 2040], [2340, 3360], [3720, 4920]],
    token1: [[-300, 0], [-1020, -480], [-2040, -1260], [-3360, -2340], [-4920, -3720]],
    allocated: [30_200n, 58_500n, 143_400n, 284_900n, 483_003n],
  },
};

function opening(launchedTokenIsQuote, tickSpacing = 60, overrides = {}) {
  return deriveLaunchPoolRecipe({ pairedTokenDecimals: 18, pairedTokenUsdPriceX18: 10n ** 18n,
    targetMarketCapUsdX18: 5_000n * 10n ** 18n, supply: SUPPLY, tokenBudget: SUPPLY / 2n,
    launchedTokenIsQuote, fee: 3000, tickSpacing, ...overrides });
}

function ranges(launchedTokenIsQuote, venue, distributionPreset, tokenBudget = SUPPLY / 2n + 3n, overrides = {}) {
  return deriveLaunchPositionRanges({ launchSqrtPriceX96: Q96, launchedTokenIsQuote,
    tokenBudget, tickSpacing: 60, venue, distributionPreset, ...overrides });
}

// A single exact rational ceiling is independently equivalent to the Solidity
// SqrtPriceMath mint debit, including amount0's two successive ceiling divisions.
function mintDebit(liquidity, lower, upper, token0) {
  return token0 ? ceil(liquidity * Q96 * (upper - lower), lower * upper)
    : ceil(liquidity * (upper - lower), Q96);
}

function fundableLiquidity(cap, lower, upper, token0) {
  return token0 ? cap * lower * upper / (Q96 * (upper - lower))
    : cap * Q96 / (upper - lower);
}

function endpointGross(positions) {
  const gross = new Map();
  for (const { tickLower, tickUpper, liquidity } of positions) {
    gross.set(tickLower, (gross.get(tickLower) ?? 0n) + liquidity);
    gross.set(tickUpper, (gross.get(tickUpper) ?? 0n) + liquidity);
  }
  return gross;
}

for (const token0 of [true, false]) {
  for (const venue of ["abyss", "uniswap-v4"]) {
    test(`${venue} token${token0 ? 0 : 1} adjacent Staircase preserves shelves without empty tick intervals`, () => {
      const options = { staircaseBoundaries: "adjacent" };
      const result = ranges(token0, venue, "staircase", 1_000_003n, options);
      const expected = token0
        ? [[0, 360], [360, 720], [720, 1380], [1380, 2460], [2460, 3840]]
        : [[-360, 0], [-720, -360], [-1380, -720], [-2460, -1380], [-3840, -2460]];
      assert.deepEqual(result.positions.map(({ tickLower, tickUpper }) => [tickLower, tickUpper]), expected);
      assert.deepEqual(result.positions.map(({ inventoryBps }) => inventoryBps), [323, 322, 1290, 2904, 5161]);
      assert.deepEqual(result.positions.map(({ allocatedTokenAmount }) => allocatedTokenAmount),
        [32_300n, 32_200n, 129_000n, 290_400n, 516_103n]);
      const tail = ranges(token0, venue, "staircase", 1_000_003n,
        { ...options, extendFinalRangeToBoundary: true });
      assert.deepEqual(tail.positions.slice(0, 4), result.positions.slice(0, 4));
      assert.equal(token0 ? tail.positions[4].tickLower : tail.positions[4].tickUpper,
        token0 ? result.positions[4].tickLower : result.positions[4].tickUpper);
      assert.equal(token0 ? tail.positions[4].tickUpper : tail.positions[4].tickLower, tail.boundaryTick);
      for (const gross of endpointGross(tail.positions).values()) assert(gross <= tail.maxLiquidityPerTick);
    });
  }
}

test("invalid or misplaced Staircase boundary choices cannot silently select a different topology", () => {
  for (const staircaseBoundaries of [null, "overlap", "", 0, true]) {
    assert.throws(() => ranges(true, "uniswap-v4", "staircase", SUPPLY / 2n, { staircaseBoundaries }));
  }
  assert.throws(() => ranges(true, "abyss", "smooth-ramp", SUPPLY / 2n, { staircaseBoundaries: "adjacent" }));
});

for (const [preset, topology] of Object.entries(TOPOLOGIES)) {
  for (const token0 of [true, false]) {
    for (const venue of ["abyss", "uniswap-v4"]) {
      test(`${venue} token${token0 ? 0 : 1} ${preset} matches literal five-position source geometry and allocations`, () => {
        const budget = 1_000_003n;
        const result = ranges(token0, venue, preset, budget);
        const ticks = token0 ? topology.token0 : topology.token1;
        assert.equal(result.launchTick, 0);
        assert.equal(result.launchSqrtPriceX96, Q96);
        assert.equal(result.positions.length, 5);
        assert.deepEqual(result.positions.map(({ tickLower, tickUpper }) => [tickLower, tickUpper]), ticks);
        assert.deepEqual(result.positions.map(({ inventoryBps }) => inventoryBps), topology.weights);
        assert.deepEqual(result.positions.map(({ allocatedTokenAmount }) => allocatedTokenAmount), topology.allocated);
        assert.deepEqual(result.positions.map(({ tickLower, tickUpper }) => (tickUpper - tickLower) / 60), topology.widths);
        assert.deepEqual(result.positions.slice(1).map((position, index) => token0
          ? (position.tickLower - result.positions[index].tickUpper) / 60
          : (result.positions[index].tickLower - position.tickUpper) / 60), topology.gaps);
        assert.equal(sum(result.positions, "allocatedTokenAmount"), budget);

        let expectedDebit = 0n;
        let expectedLiquidity = 0n;
        for (const [index, position] of result.positions.entries()) {
          const [tickLower, tickUpper] = ticks[index];
          const lower = getSqrtRatioAtTick(tickLower);
          const upper = getSqrtRatioAtTick(tickUpper);
          const liquidity = fundableLiquidity(topology.allocated[index], lower, upper, token0);
          const debit = mintDebit(liquidity, lower, upper, token0);
          assert.equal(position.sqrtPriceLowerX96, lower);
          assert.equal(position.sqrtPriceUpperX96, upper);
          assert.equal(position.liquidity, liquidity);
          assert.equal(position.maxTokenAmount, topology.allocated[index], "Admission commits the entire intended cap, including mint dust");
          assert(debit > 0n && debit <= topology.allocated[index]);
          assert(mintDebit(position.liquidity + 1n, lower, upper, token0) > topology.allocated[index],
            "No additional liquidity unit fits the allocated inventory budget");
          assert.equal(position.maxQuoteAmount, 0n);
          assert(position.liquidity > 0n && position.liquidity <= MAX_INT128);
          assert.equal(Math.abs(position.tickLower % 60), 0);
          assert.equal(Math.abs(position.tickUpper % 60), 0);
          expectedDebit += debit;
          expectedLiquidity += liquidity;
        }
        assert.equal(result.tokenAmountMaximum, budget);
        assert.equal(result.unspentTokenAmount, budget - expectedDebit);
        assert.equal(result.totalLiquidity, expectedLiquidity);
        assert.equal(result.buySideLiquidity, result.positions[0].liquidity);
        assert.equal(result.openingActiveLiquidity, token0 ? result.positions[0].liquidity : 0n);
        assert(result.buySideLiquidity < result.totalLiquidity, "Disjoint positions are not all active at the opening");
        const boundary = token0 ? 887_220 : -887_220;
        assert.equal(result.boundaryTick, boundary);
        assert.equal(result.boundarySqrtPriceX96, getSqrtRatioAtTick(boundary));
        assert.notEqual(token0 ? result.positions.at(-1).tickUpper : result.positions.at(-1).tickLower, boundary,
          "Canonical presets do not silently extrapolate to infinity");
        assert.equal(result.maxLiquidityPerTick, MAX_UINT128 / (venue === "abyss" ? 29_575n : 29_576n));
        assert([...endpointGross(result.positions).values()].every((gross) => gross <= result.maxLiquidityPerTick));
        assert.deepEqual(ranges(token0, venue, preset, budget, { extendFinalRangeToBoundary: false }), result);
      });

      test(`${venue} token${token0 ? 0 : 1} ${preset} tail opt-in extends only the fifth far endpoint`, () => {
        const canonical = ranges(token0, venue, preset);
        const extended = ranges(token0, venue, preset, SUPPLY / 2n + 3n, { extendFinalRangeToBoundary: true });
        assert.deepEqual(extended.positions.slice(0, 4), canonical.positions.slice(0, 4));
        const before = canonical.positions.at(-1);
        const after = extended.positions.at(-1);
        assert.equal(after.inventoryBps, before.inventoryBps);
        assert.equal(after.allocatedTokenAmount, before.allocatedTokenAmount);
        assert.equal(token0 ? after.tickLower : after.tickUpper, token0 ? before.tickLower : before.tickUpper);
        assert.equal(token0 ? after.tickUpper : after.tickLower, token0 ? 887_220 : -887_220);
        assert(after.tickLower < after.tickUpper && after.tickLower >= -887_272 && after.tickUpper <= 887_272);
        assert.equal(Math.abs(after.tickLower % 60), 0);
        assert.equal(Math.abs(after.tickUpper % 60), 0);
        assert.equal(after.maxTokenAmount, after.allocatedTokenAmount);
        assert(mintDebit(after.liquidity, after.sqrtPriceLowerX96, after.sqrtPriceUpperX96, token0) <= after.maxTokenAmount);
        assert(after.maxTokenAmount > 0n && after.maxTokenAmount <= after.allocatedTokenAmount);
        assert(mintDebit(after.liquidity + 1n, after.sqrtPriceLowerX96, after.sqrtPriceUpperX96, token0) > after.allocatedTokenAmount,
          "The extended tail must consume the maximum fundable inventory, without a percentage reserve");
        assert(after.liquidity < before.liquidity);
        assert.equal(extended.buySideLiquidity, canonical.buySideLiquidity);
        assert.equal(extended.openingActiveLiquidity, canonical.openingActiveLiquidity);
        assert.equal(extended.tokenAmountMaximum, SUPPLY / 2n + 3n);
        assert.equal(extended.boundarySqrtPriceX96, token0 ? after.sqrtPriceUpperX96 : after.sqrtPriceLowerX96);
        assert(extended.boundarySqrtPriceX96 > 4_295_128_739n);
        assert(extended.boundarySqrtPriceX96 < 1_461_446_703_485_210_103_287_273_052_203_988_822_378_723_970_342n);
        assert(Math.abs(extended.boundaryTick + (token0 ? 60 : -60)) > 887_272);
      });
    }
  }
}

test("every supported count preserves positive weights, 64 active steps and floor/remainder allocations", () => {
  const budget = 10n ** 24n + 19n;
  for (const preset of Object.keys(TOPOLOGIES)) {
    for (let positionCount = 2; positionCount <= 16; positionCount += 1) {
      for (const token0 of [true, false]) {
        for (const venue of ["abyss", "uniswap-v4"]) {
          const result = ranges(token0, venue, preset, budget, { positionCount });
          assert.equal(result.positions.length, positionCount);
          assert.equal(result.positions.reduce((total, position) => total + position.inventoryBps, 0), 10_000);
          assert.equal(result.positions.reduce((total, position) => total + (position.tickUpper - position.tickLower) / 60, 0), 64);
          assert.equal(sum(result.positions, "allocatedTokenAmount"), budget);
          assert.equal(sum(result.positions, "maxTokenAmount"), budget);
          assert.equal(result.tokenAmountMaximum, budget);
          let allocated = 0n;
          for (const [index, position] of result.positions.entries()) {
            assert(Number.isInteger(position.inventoryBps) && position.inventoryBps > 0);
            assert(position.allocatedTokenAmount > 0n && position.liquidity > 0n);
            assert(position.maxTokenAmount > 0n && position.maxTokenAmount <= position.allocatedTokenAmount);
            assert.equal(position.allocatedTokenAmount, index === positionCount - 1
              ? budget - allocated : budget * BigInt(position.inventoryBps) / 10_000n);
            allocated += position.allocatedTokenAmount;
            assert(token0 ? position.tickLower >= 0 : position.tickUpper <= 0);
            if (index > 0) {
              const previous = result.positions[index - 1];
              const gap = token0 ? position.tickLower - previous.tickUpper : previous.tickLower - position.tickUpper;
              assert(gap >= 0);
              if (preset === "smooth-ramp") assert.equal(gap, 0);
              if (preset === "early-scarcity") assert(gap > 0);
              if (preset === "staircase") assert(gap === 0 || gap === 180);
            }
          }
        }
      }
    }
  }
});

test("two source-defined pool shares retain exact mint dust without charging the inventory twice", () => {
  const perPoolBudget = 1_000_003n;
  for (const token0 of [true, false]) {
    const recipe = opening(token0);
    const pools = [ranges(token0, "abyss", "smooth-ramp", perPoolBudget, { launchSqrtPriceX96: recipe.launchSqrtPriceX96 }),
      ranges(token0, "uniswap-v4", "staircase", perPoolBudget, { launchSqrtPriceX96: recipe.launchSqrtPriceX96 })];
    for (const pool of pools) {
      assert(pool.unspentTokenAmount > 0n);
      const expectedDebits = pool.positions.map((position) => mintDebit(position.liquidity,
        getSqrtRatioAtTick(position.tickLower), getSqrtRatioAtTick(position.tickUpper), token0));
      assert.deepEqual(pool.positions.map((position) => position.maxTokenAmount),
        pool.positions.map((position) => position.allocatedTokenAmount));
      assert.equal(pool.unspentTokenAmount, pool.positions.reduce((dust, position, index) =>
        dust + position.allocatedTokenAmount - expectedDebits[index], 0n));
      assert.equal(pool.tokenAmountMaximum, perPoolBudget);
      assert(pool.positions.some((position) => {
        const lower = getSqrtRatioAtTick(position.tickLower);
        const upper = getSqrtRatioAtTick(position.tickUpper);
        const numerator = token0 ? position.liquidity * Q96 * (upper - lower) : position.liquidity * (upper - lower);
        const denominator = token0 ? lower * upper : Q96;
        return numerator % denominator !== 0n && ceil(numerator, denominator) <= position.maxTokenAmount;
      }), "Fractional mint debits must round UP, not become unsafe floor maxima");
    }
    assert.equal(pools.reduce((total, pool) => total + pool.tokenAmountMaximum, 0n), 2n * perPoolBudget);
  }
});

test("negative alignment uses -887200 at spacing 200 and token1 activates only its first reachable band", () => {
  const recipe = opening(false, 200);
  for (const venue of ["abyss", "uniswap-v4"]) {
    const result = ranges(false, venue, "staircase", SUPPLY / 2n, { tickSpacing: 200,
      launchSqrtPriceX96: recipe.launchSqrtPriceX96, extendFinalRangeToBoundary: true });
    assert.equal(result.boundaryTick, -887_200);
    assert.equal(result.positions.at(-1).tickLower, -887_200);
    assert.equal(result.openingActiveLiquidity, 0n);
    assert.equal(result.buySideLiquidity, result.positions[0].liquidity);
    assert(result.buySideLiquidity > 0n && result.buySideLiquidity < result.totalLiquidity);
    assert.equal(result.maxLiquidityPerTick, MAX_UINT128 / (venue === "abyss" ? 8_873n : 8_874n));
  }
  for (const token0 of [true, false]) {
    const result = ranges(token0, "abyss", "smooth-ramp", SUPPLY / 2n, { launchSqrtPriceX96: getSqrtRatioAtTick(-60) });
    assert.equal(result.launchTick, -60);
    assert.deepEqual(result.positions.map(({ tickLower, tickUpper }) => [tickLower, tickUpper]), token0
      ? [[-60, 900], [900, 1740], [1740, 2520], [2520, 3180], [3180, 3780]]
      : [[-1020, -60], [-1860, -1020], [-2640, -1860], [-3300, -2640], [-3900, -3300]]);
  }
});

test("disjoint bands may exceed a single tick capacity in total when every endpoint gross fits", () => {
  for (const venue of ["abyss", "uniswap-v4"]) {
    const capacity = MAX_UINT128 / (venue === "abyss" ? 29_575n : 29_576n);
    for (const token0 of [true, false]) {
      for (const [preset, divisor] of [["smooth-ramp", 24n], ["staircase", 12n], ["early-scarcity", 12n]]) {
        const result = ranges(token0, venue, preset, capacity / divisor);
        assert(result.totalLiquidity > capacity);
        assert(result.positions.every((position) => position.liquidity < capacity));
        const gross = endpointGross(result.positions);
        assert([...gross.values()].every((value) => value <= capacity));
        assert.equal(gross.get(0), result.positions[0].liquidity,
          "Only the first band's gross liquidity belongs to the opening endpoint");
        if (preset === "smooth-ramp") {
          assert.equal(gross.size, 6);
          for (let index = 0; index < 4; index += 1) {
            const sharedTick = token0 ? result.positions[index].tickUpper : result.positions[index].tickLower;
            assert.equal(gross.get(sharedTick), result.positions[index].liquidity + result.positions[index + 1].liquidity);
          }
        }
        if (preset === "staircase") {
          assert.equal(gross.size, 9);
          assert.equal(gross.get(token0 ? 360 : -360), result.positions[0].liquidity + result.positions[1].liquidity);
        }
        if (preset === "early-scarcity") assert.equal(gross.size, 10);
      }
    }
  }
});

test("a later shared endpoint rejects gross overflow even when all individual mint liquidities fit", () => {
  const topology = TOPOLOGIES["smooth-ramp"];
  for (const venue of ["abyss", "uniswap-v4"]) {
    const capacity = MAX_UINT128 / (venue === "abyss" ? 29_575n : 29_576n);
    const budget = capacity / 18n;
    for (const token0 of [true, false]) {
      const ticks = token0 ? topology.token0 : topology.token1;
      let allocated = 0n;
      const expected = ticks.map(([tickLower, tickUpper], index) => {
        const cap = index === 4 ? budget - allocated : budget * BigInt(topology.weights[index]) / 10_000n;
        allocated += cap;
        return { tickLower, tickUpper, liquidity: fundableLiquidity(cap,
          getSqrtRatioAtTick(tickLower), getSqrtRatioAtTick(tickUpper), token0, venue) };
      });
      assert(expected.every((position) => position.liquidity < capacity && position.liquidity <= MAX_INT128));
      const gross = endpointGross(expected);
      const failingTick = token0 ? 3240 : -3240;
      assert(gross.get(failingTick) > capacity);
      assert([...gross.entries()].every(([tick, liquidity]) => tick === failingTick || liquidity <= capacity));
      assert.throws(() => ranges(token0, venue, "smooth-ramp", budget), new RegExp(`tick capacity at ${failingTick}`));
    }
  }
});

test("positive allocated caps do not authorize zero liquidity or int128 mint overflow", () => {
  for (const venue of ["abyss", "uniswap-v4"]) {
    assert.throws(() => ranges(true, venue, "smooth-ramp", MAX_UINT256), /int128 mint range/);
    // Even nonzero caps cannot fund an integer unit of liquidity at this price.
    assert.throws(() => ranges(true, venue, "smooth-ramp", 10_000n,
      { launchSqrtPriceX96: getSqrtRatioAtTick(-800_040) }), /positive int128 mint range/);
    assert.throws(() => ranges(false, venue, "smooth-ramp", 10_000n,
      { launchSqrtPriceX96: getSqrtRatioAtTick(800_040) }), /positive int128 mint range/);
  }
});

test("V4 signed settlement rejects token debits beyond int128 even when endpoint capacity and Abyss liquidity fit", () => {
  const tokenBudget = MAX_INT128 * 10n;
  const recipe = opening(false, 60, { supply: 10n ** 40n, tokenBudget });
  const overrides = { launchSqrtPriceX96: recipe.launchSqrtPriceX96 };
  const abyss = ranges(false, "abyss", "smooth-ramp", tokenBudget, overrides);
  assert([...endpointGross(abyss.positions).values()].every((gross) => gross < abyss.maxLiquidityPerTick));
  assert(abyss.positions.every((position) => position.liquidity < MAX_INT128));
  assert(abyss.positions.some((position) => position.maxTokenAmount > MAX_INT128));
  assert.throws(() => ranges(false, "uniswap-v4", "smooth-ramp", tokenBudget, overrides), /settlement range/);
});

test("presets reject insufficient room rather than scaling arbitrary equal tick bands to the boundary", () => {
  for (const extendFinalRangeToBoundary of [false, true]) {
    for (const token0 of [true, false]) {
      for (const preset of Object.keys(TOPOLOGIES)) {
        assert.throws(() => ranges(token0, "abyss", preset, SUPPLY / 2n, {
          launchSqrtPriceX96: getSqrtRatioAtTick(token0 ? 887_160 : -887_160), extendFinalRangeToBoundary,
        }), /too little room/);
      }
    }
  }
  // Smooth Ramp needs exactly 64 steps. One step less must reject, not shrink
  // the final band even when the caller opted into tail extension.
  for (const token0 of [true, false]) {
    const fittingTick = token0 ? 883_380 : -883_380;
    const fittingBudget = 10n ** 8n;
    const result = ranges(token0, "abyss", "smooth-ramp", fittingBudget,
      { launchSqrtPriceX96: getSqrtRatioAtTick(fittingTick) });
    assert.equal(token0 ? result.positions.at(-1).tickUpper : result.positions.at(-1).tickLower, token0 ? 887_220 : -887_220);
    assert.deepEqual(ranges(token0, "abyss", "smooth-ramp", fittingBudget,
      { launchSqrtPriceX96: getSqrtRatioAtTick(fittingTick), extendFinalRangeToBoundary: true }), result);
    assert.throws(() => ranges(token0, "abyss", "smooth-ramp", fittingBudget, {
      launchSqrtPriceX96: getSqrtRatioAtTick(fittingTick + (token0 ? 60 : -60)), extendFinalRangeToBoundary: true,
    }), /too little room/);
  }
});

test("invalid prices, presets, counts, flags and budgets cannot produce launch mint instructions", () => {
  const input = { launchSqrtPriceX96: Q96, launchedTokenIsQuote: true,
    tokenBudget: SUPPLY / 2n, tickSpacing: 60, venue: "abyss", distributionPreset: "smooth-ramp" };
  for (const changes of [
    { launchSqrtPriceX96: Q96 + 1n },
    { launchSqrtPriceX96: getSqrtRatioAtTick(1) },
    { launchSqrtPriceX96: 0n },
    { launchSqrtPriceX96: getSqrtRatioAtTick(887_272) },
    { launchSqrtPriceX96: MAX_UINT256 },
    { tokenBudget: -1n }, { tokenBudget: 0n }, { tokenBudget: 1n }, { tokenBudget: MAX_UINT256 + 1n },
    { launchedTokenIsQuote: "true" },
    { distributionPreset: undefined }, { distributionPreset: "nested" }, { distributionPreset: "default" },
    { positionCount: 0 }, { positionCount: -1 }, { positionCount: 1 }, { positionCount: 1.5 }, { positionCount: 17 },
    { tickSpacing: 0 }, { tickSpacing: -60 }, { tickSpacing: 60.5 }, { tickSpacing: 32768 },
    { venue: "unregistered" },
    { extendFinalRangeToBoundary: "true" }, { extendFinalRangeToBoundary: 1 },
  ]) assert.throws(() => deriveLaunchPositionRanges({ ...input, ...changes }));
});
